### PR TITLE
[ContributorsFromGit] -> [Git::Contributors]

### PR DESCRIPTION
**Pull request by karenetheridge**
The latter has fewer prerequisites and does not have issues on MSWin32.

### CODE REVIEW

**Comment by karenetheridge** [comment]
BTW, your main branch is configured on github as 'releases', not 'master', so that's the branch my fork defaulted to, and also the branch that the pull request wanted to merge to. That doesn't look right, as it only holds build output -- it looks like development is supposed to be made with respect to master?

**Comment by yanick** [comment]
[releases vs master] That's not a goof, but done purposefully. 

With the main branch on GitHub being the post-dzil'ed one, it leveragea the dzil-generated README.mkd, and for people who are less comfortable with dzil they can just work with the code of 'releases' as-is, and I can take care to port any patch to the master.

**Comment by karenetheridge** [comment]
> [releases vs master] That's not a goof, but done purposefully.
> With the main branch on GitHub being the post-dzil'ed one, it leveragea the dzil-generated README.mkd, and for people who are less comfortable with dzil they can just work with the code of 'releases' as-is, and I can take care to port any patch to the master.

Aha, that makes sense -- at least it does for any commit that doesn't involve dzil configs themselves ^_^

**Comment by yanick** [comment]
Heh, indeed. But then, it's... ah, I'll go with "rare"... that somebody send a PR for the dist.ini of a distro. :-)

Btw, merged and pushed to CPAN. Thanks!

**Comment by karenetheridge** [comment]
thanks!  I +1'd you on irc for it :)

**Pull request merged**
